---
version: 0.1.0
extraKubeletArgs:
  --cluster-domain: cluster.local
  --cluster-dns: 10.152.183.10
addons:
  - name: dns
  - name: hostpath-storage
  - name: metallb
    args: [192.168.1.200-192.168.1.210]    